[package]
name = "ip3"
version = "1.0.0"
edition = "2021"

description = "Convert between three words and IPV4 addresses"
license = "LGPL-2.1-only"
readme = "README.md"

[features]
default=["en"]
en = []

[dependencies]
bitvec = "1.0.1"
const-str = "0.5.6"
